# Generated by Django 4.2.5 on 2023-10-26 14:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0003_alter_bookreviewticket_book_image_delete_review"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookreview",
            old_name="created_at",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="bookreviewticket",
            old_name="created_date",
            new_name="date",
        ),
    ]
