# Generated by Django 4.2.5 on 2023-10-26 14:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0004_rename_created_at_bookreview_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookreviewticket",
            old_name="text",
            new_name="request_text",
        ),
    ]
